### ISSUE TITLE
scss files disconnected

### ISSUE THREAD

**Issue by matttk** [Frojd/react-sass-starterkit#16]
I noticed that I was only getting CSS from my top-level component, which was included in the index.scss. However, any components that were child components were not included in the built version.

I solved this by adding imports (e.g. index.scss imports topLevel.scss, which imports subComponent.scss, which imports subSubComponent.scss).

Is this not how it should be generated when you add a new subcomponent?

**Comment by iksototh** [comment]
Currently it is done manually so it is up to the creator to add the scss files, either by as you are mentioning by importing them in the parent scss file or by adding them to the components.scss file.

We usually add them to the components.scss file manually instead of the parent file, and I will make a change in an upcoming version so that is the default behavior when creating subcomponents.
